import type { Project } from "./types";

function clip(
  id: string,
  startSec: number,
  endSec: number,
  hook: string,
  title: string,
  caption: string,
  keywords: string[],
  viralScore: number,
  why: string,
  hashtags: string[],
) {
  return {
    id,
    startSec,
    endSec,
    hook,
    title,
    caption,
    keywords,
    viralScore,
    why,
    hashtags,
    platforms: ["tiktok" as const, "shorts" as const, "reels" as const],
    status: "ready" as const,
  };
}

export const SAMPLES: Project[] = [
  {
    id: "sample-founder",
    title: "Dari Rp0, clip orang 12 jam sehari",
    thumbnail: "/media/podcast.jpg",
    durationSec: 42 * 60,
    language: "id",
    captionStyle: "hormozi",
    aspect: "9:16",
    createdAt: "2026-08-20T09:00:00.000Z",
    status: "ready",
    transcript: `[00:18] Gue dulu nge-clip video orang 12 jam sehari. Bayarannya 50 ribu.
[01:02] Bukan 50 ribu per jam. 50 ribu per hari.
[03:40] Yang berubah bukan tools-nya. Yang berubah: gue berhenti nunggu brief.
[04:12] Satu podcast, gue tarik 30 momen. 30 hari konten. Selesai.
[08:55] Orang kira clipping itu edit. Clipping itu dengerin, terus berani motong.
[12:20] Hook di detik pertama. Kalau gak nahan di detik 1, skip.
[18:04] Jangan rapi. Rapi itu musuh retensi.
[22:11] Caption itu bukan subtitle. Caption itu punchline yang kebakar di layar.
[29:40] Kamu gak butuh 10.000 followers. Kamu butuh 10 clip yang orang pause.
[36:02] Kalau transkripnya ada, agent bisa ngerjain 80% kerjaan. Sisanya selera.`,
    clips: [
      clip(
        "sf-1",
        18,
        62,
        "50 ribu. Sehari. Bukan sejam.",
        "Gaji clipper yang bikin orang kaget",
        "GUE CLIP 12 JAM  BAYARAN 50 RIBU  SEHARI",
        ["12 JAM", "50 RIBU", "SEHARI"],
        94,
        "Angka + ketidakadilan di 3 detik pertama. Pause bait klasik.",
        ["#clipper", "#konten", "#sidehustle"],
      ),
      clip(
        "sf-2",
        220,
        262,
        "Berhenti nunggu brief.",
        "Satu podcast = 30 hari konten",
        "SATU PODCAST  30 MOMEN  30 HARI KONTEN",
        ["SATU PODCAST", "30 HARI"],
        91,
        "Promise konkret. Framework yang bisa di-screenshot.",
        ["#podcast", "#contentops", "#ai"],
      ),
      clip(
        "sf-3",
        532,
        568,
        "Clipping bukan edit.",
        "Kerjaannya dengerin, lalu motong",
        "CLIPPING BUKAN EDIT  ITU DENGERIN  LALU BERANI MOTONG",
        ["BUKAN EDIT", "BERANI MOTONG"],
        86,
        "Reframe identitas. Clippers ngerasa kelihatan.",
        ["#editing", "#creator"],
      ),
      clip(
        "sf-4",
        740,
        778,
        "Hook di detik pertama.",
        "Kalau gak nahan di detik 1, skip",
        "HOOK DETIK PERTAMA  GAK TAHAN  SKIP",
        ["DETIK PERTAMA", "SKIP"],
        89,
        "Aturan retensi yang bisa langsung dipake.",
        ["#tiktoktips", "#retention"],
      ),
      clip(
        "sf-5",
        1320,
        1368,
        "10 clip yang orang pause.",
        "Gak butuh 10.000 followers dulu",
        "GAK BUTUH 10.000 FOLLOWERS  BUTUH 10 CLIP  YANG ORANG PAUSE",
        ["10.000 FOLLOWERS", "PAUSE"],
        92,
        "Melepas tekanan follower-count. Actionable.",
        ["#growth", "#shortform"],
      ),
    ],
  },
  {
    id: "sample-stack",
    title: "The $0 clipping stack",
    thumbnail: "/media/rooftop.jpg",
    durationSec: 38 * 60,
    language: "en",
    captionStyle: "box",
    aspect: "9:16",
    createdAt: "2026-08-18T14:00:00.000Z",
    status: "ready",
    transcript: `[00:40] Everyone is paying for a clipping agent. You do not have to.
[01:22] The expensive part is not the model. It is the transcode farm.
[04:50] Transcript in. Viral moments out. Captions burned as text, not as a render.
[09:10] If you already have YouTube captions, you already have the raw material.
[14:33] A good clip is 18 to 35 seconds. Anything longer is a trailer.
[19:02] First line has to be a claim, a number, or an insult to the status quo.
[24:18] Hashtags do not save a weak hook. Kill the first three seconds.
[31:40] Queue the posts. Do not auto-publish until you have watched the cut.`,
    clips: [
      clip(
        "st-1",
        40,
        82,
        "You do not have to pay for a clipping agent.",
        "The $0 stack nobody explains",
        "EVERYONE PAYS  FOR A CLIPPING AGENT  YOU DO NOT HAVE TO",
        ["EVERYONE PAYS", "DO NOT HAVE TO"],
        93,
        "Contrarian opener. Instant save.",
        ["#ai", "#clipping", "#creator"],
      ),
      clip(
        "st-2",
        290,
        338,
        "The expensive part is the transcode farm.",
        "Models are cheap. Renders are not.",
        "THE MODEL IS CHEAP  THE TRANSCODE FARM  IS WHAT YOU PAY FOR",
        ["CHEAP", "TRANSCODE FARM"],
        88,
        "Industry secret framing. Feels like insider talk.",
        ["#startups", "#aiagents"],
      ),
      clip(
        "st-3",
        873,
        918,
        "18 to 35 seconds. Longer is a trailer.",
        "The only length that retains",
        "A GOOD CLIP IS  18 TO 35 SECONDS  LONGER IS A TRAILER",
        ["18 TO 35", "TRAILER"],
        90,
        "Hard rule. Screenshot-able.",
        ["#shortform", "#editing"],
      ),
      clip(
        "st-4",
        1142,
        1188,
        "A claim, a number, or an insult.",
        "What the first line must do",
        "FIRST LINE  A CLAIM  A NUMBER  OR AN INSULT",
        ["CLAIM", "NUMBER", "INSULT"],
        87,
        "Three-beat list. Easy to stitch.",
        ["#hooks", "#copywriting"],
      ),
      clip(
        "st-5",
        1900,
        1948,
        "Do not auto-publish until you watch the cut.",
        "Queue beats autopilot",
        "QUEUE THE POSTS  DO NOT AUTO-PUBLISH  UNTIL YOU WATCH",
        ["QUEUE", "WATCH"],
        84,
        "Trust-building closer for agencies.",
        ["#agency", "#workflow"],
      ),
    ],
  },
  {
    id: "sample-roast",
    title: "Roast: startup advice that aged badly",
    thumbnail: "/media/comedy.jpg",
    durationSec: 51 * 60,
    language: "en",
    captionStyle: "glow",
    aspect: "9:16",
    createdAt: "2026-08-12T19:30:00.000Z",
    status: "ready",
    transcript: `[02:10] Follow your passion. That is how you get a passion and no rent.
[06:44] Move fast and break things. We did. Legal sent a letter.
[11:02] The customer is always right. The customer is often bored.
[17:30] Hire slow, fire fast. Cool. Who is doing the work on Tuesday.
[25:18] If you build it they will come. They did not.
[33:40] Hustle harder. You are already tired. The funnel is the problem.
[41:05] Fake it till you make it. Please stop. The clip will outlive you.`,
    clips: [
      clip(
        "sr-1",
        130,
        168,
        "A passion. And no rent.",
        "Follow your passion, they said",
        "FOLLOW YOUR PASSION  THAT IS HOW YOU GET  A PASSION AND NO RENT",
        ["PASSION", "NO RENT"],
        96,
        "Punchline lands on the third line. Comedy retention.",
        ["#startup", "#roast"],
      ),
      clip(
        "sr-2",
        404,
        448,
        "We did. Legal sent a letter.",
        "Move fast and break things",
        "MOVE FAST  AND BREAK THINGS  LEGAL SENT A LETTER",
        ["BREAK THINGS", "LEGAL"],
        91,
        "Callback to a dead slogan. Share bait.",
        ["#founder", "#comedy"],
      ),
      clip(
        "sr-3",
        662,
        708,
        "The customer is often bored.",
        "Always right? No.",
        "THE CUSTOMER IS ALWAYS RIGHT  THE CUSTOMER  IS OFTEN BORED",
        ["ALWAYS RIGHT", "BORED"],
        88,
        "Flip of a proverb. Clean three-liner.",
        ["#product", "#roast"],
      ),
      clip(
        "sr-4",
        1518,
        1560,
        "They did not.",
        "If you build it they will come",
        "IF YOU BUILD IT  THEY WILL COME  THEY DID NOT",
        ["THEY WILL COME", "DID NOT"],
        90,
        "Deadpan last line. High rewatch.",
        ["#buildinpublic"],
      ),
      clip(
        "sr-5",
        2465,
        2510,
        "The clip will outlive you.",
        "Fake it till you make it",
        "FAKE IT TILL YOU MAKE IT  PLEASE STOP  THE CLIP WILL OUTLIVE YOU",
        ["PLEASE STOP", "OUTLIVE YOU"],
        93,
        "Dark closer. Perfect for the last slide of a series.",
        ["#creator", "#warning"],
      ),
    ],
  },
];
